data_path: "../../datasets/MVTEC"
backbone: "efficientnet_b5" 
embed_dim: 64
out_indice: [3, 4] 
obj: tile
phase: train 
save_path: "./results"
TrainingData:
  epochs: 10
  batch_size: 8 
  lr: 0.0004 
  img_size: 224 
  crop_size: 224 
